apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/jmmclean/argocd-gameday.git
    targetRevision: main
    path: argo-rollouts/local/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
