if k8s_context() != 'minikube':
  fail("K8s context is not minikube")

allow_k8s_contexts(contexts = ["minikube"])

local_resource(name = 'external-secrets-ns',
    cmd = 'kubectl get namespace | grep -q "^external-secrets" || kubectl create namespace external-secrets',
    labels = ["external-secrets"]
)
