apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: 'sample'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - https://github.com/gfliker/argocd-gameday
